/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.szczad.my_project.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
